[package]
name = "dominion"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"

[lints.clippy]
nursery = { level = "warn", priority = -1 }
manual_let_else = "warn"
str_to_string = "warn"
string_to_string = "warn"
